management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: "*"
    metrics:
        export:
            graphite:
                enabled: false
            prometheus:
                enabled: true
            simple:
                enabled: false

spring:
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: ${spring.application.name}

server:
  port: 8296
  
vnfmdriver:
  topics:
    lcmOpOccPollingTopic: lcm_op_occ_polling_requests
    lifecycleResponsesTopic: lm_vnfc_lifecycle_execution_events
  packageManagement:
    enabled: false
    imageArtifactFilter: Files/Images
    # url should be in the form 'http://hostname/path/{vnfPackageId}'
    packageRepositoryUrl:  
  grant:
    automatic: true
    provider:
      url:

ribbon:
  eureka:
    enabled: true
  # Set timeout on Zuul proxy to 20 seconds
  ReadTimeout: 20000
  ConnectTimeout: 20000

ishtar:
  ribbon:
    listOfServers: ishtar:8280
    IsSecure: true

endpoints.routes.sensitive: false

zuul:
  # sensitiveHeaders deliberately empty to forward all headers
  sensitive-headers:
  routes:
    package-management:
      path: /vnfpkgm/v1/vnf_packages/**
      serviceId: ishtar
      stripPrefix: false