management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: "*"
    metrics:
        export:
            graphite:
                enabled: false
            prometheus:
                enabled: true
            simple:
                enabled: false

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      auto-offset-reset: latest
      group-id: ${spring.application.name}

server:
  port: 8296
  
vnfmdriver:
  topics:
    lcmOpOccPollingTopic: lcm_op_occ_polling_requests
    lifecycleResponsesTopic: lm_vnfc_lifecycle_execution_events
  packageManagement:
    imageArtifactFilter: Files/Images
    # url should be in the form 'http://hostname/path/{vnfPackageId}'
    packageRepositoryUrl:  
