## Global settings used across all of the LM sub-charts
global:

  ## Global Docker
  ## Enable the use of a Docker Registry to pull the application Docker Image.
  ## If registry_enabled is true then the image reference will be: global.docker.registryIp:global.docker.registryPort/docker.image:docker.version
  ## Else the image reference will be: docker.image:docker.version
  docker:
    registryEnabled: false
    imagePullPolicy: Always
    registryIp: "registry_ip"
    registryPort: 5000

  config:
    ## Label used to decide the version of configuration to read from cloud-config server
    cloudLabel: "master"
    
  ## Security
  ## Enable the use of LM security features
  security:
    enabled: false
    ## Reference to a secret containing the certificate for https enabled services
    lmCertsSecretName: 

## Docker
docker:
  ## Name of the Docker Image
  image: vnfm-driver
  ## Tagged version of the Docker Image
  version: #project.version#
  ## Pull policy on the Docker Image (when global.docker.registryEnabled is false)
  imagePullPolicy: IfNotPresent

## Application
app:
  ## Number of pods to install
  numReplicas: 1
  
  config:
    ## Runtime Profiles
    ## Included runtime profiles of the application (spring_profiles_include)
    ## Options:
    ##    - swagger: add this option to enabled swagger documentation endpoint on the application
    profiles: "prod,kubernetes"
    
    ## RM Name referenced by LM as the "type" of this RM when onboarded 
    rmName: Not_configured
    
    ## Environment Options
    ## Add environment variables to the pods
    # env: 
    
  ## Probe configuration for checking Application availability
  livenessProbe:
    failureThreshold: 3
    initialDelaySeconds: 90
    periodSeconds: 30
  readinessProbe:
    failureThreshold: 3
    initialDelaySeconds: 20
    periodSeconds: 10
  
  ## JVM Options
  ## Options to pass to the JVM when running the application
  # jvmOptions: -Xmx384m

## Service Configuration 
## Define how this application is accessed internally (and potentially externally)
service:
  type: ClusterIP
  nodePort: 31296
